import type { AnalysisReport, ComparisonReport, Job } from "../api/types";

export const completedAnalysisJob: Job = {
  id: "0123456789abcdef0123456789abcdef",
  type: "analysis",
  status: "completed",
  stage: "completed",
  progress: 100,
  message: "Analysis completed",
  inputs: [{ name: "services-agreement.txt" }],
  report_url: "/api/v1/jobs/0123456789abcdef0123456789abcdef/report",
  created_at: "2026-08-11T12:00:00Z",
  updated_at: "2026-08-11T12:00:02Z",
  completed_at: "2026-08-11T12:00:02Z",
};

export const analysisReport: AnalysisReport = {
  schema_version: "1.0",
  document_id: completedAnalysisJob.id,
  file_path: "services-agreement.txt",
  title: "SERVICES AGREEMENT",
  document_type: "Service Agreement",
  summary: "Analyzed 2 clauses and accepted 2 evidence-backed findings.",
  clauses: [
    {
      id: "clause-001",
      order: 1,
      title: "Payment",
      text: "Customer shall pay all invoices within thirty days.",
      category: "Payment",
      risk_terms: [],
    },
    {
      id: "clause-002",
      order: 2,
      title: "Termination",
      text: "Provider may terminate in its sole discretion.",
      category: "Termination",
      risk_terms: ["sole discretion"],
    },
  ],
  entities: [{ text: "Customer", label: "PARTY", source: "heuristic" }],
  evidence: [],
  findings: [
    {
      id: "finding-1",
      issue_type: "risky_language",
      severity: "HIGH",
      clause_id: "clause-002",
      clause_title: "Termination",
      explanation: "The termination right is unilateral and lacks objective limits.",
      rule_id: "contextual_risky_language",
      signals: ["sole discretion"],
      evidence: [
        {
          id: "evidence-1",
          source: "local_reference",
          title: "Balanced Discretion Checklist",
          text: "Unilateral discretion should use objective standards.",
          relevance: 0.86,
          clause_id: "clause-002",
        },
      ],
      component_scores: {
        deterministic_rules: 0.9,
        rag_evidence: 0.86,
        primary_reasoning: 0.82,
        verifier_agreement: 0.78,
        clause_structure: 0.8,
        final: 0.84,
        weights: {},
      },
      accepted: true,
      acceptance_threshold: 0.62,
      model_confidence: 0.82,
      verifier_confidence: 0.78,
      verifier_status: "verified",
      verifier_rationale: "The clause contains no balancing safeguard.",
      suggested_rewrite: "Either party may terminate for documented cause after notice.",
    },
    {
      id: "finding-2",
      issue_type: "payment_ambiguity",
      severity: "MEDIUM",
      clause_id: "clause-001",
      clause_title: "Payment",
      explanation: "The payment mechanism does not define invoice disputes.",
      component_scores: {
        deterministic_rules: 0.72,
        rag_evidence: 0.68,
        primary_reasoning: 0.7,
        verifier_agreement: 0.66,
        clause_structure: 0.75,
        final: 0.7,
        weights: {},
      },
      accepted: true,
      model_confidence: 0.7,
      verifier_confidence: 0.66,
    },
  ],
  rewrites: [
    {
      clause_id: "clause-002",
      original_text: "Provider may terminate in its sole discretion.",
      rewritten_text: "Either party may terminate for documented cause after notice.",
      rationale: "Adds objective and mutual safeguards.",
    },
  ],
  limitations: ["Findings require qualified legal review."],
};

export const comparisonReport: ComparisonReport = {
  schema_version: "1.0",
  comparison_id: "fedcba9876543210fedcba9876543210",
  original_document: "original.txt",
  modified_document: "modified.txt",
  original_type: "Service Agreement",
  modified_type: "Service Agreement",
  original_clause_count: 2,
  modified_clause_count: 2,
  summary: { matched: 2, changed: 1, added: 0, removed: 0 },
  clause_deltas: [
    {
      status: "changed",
      similarity: 0.72,
      original_clause_id: "clause-001",
      original_title: "Payment",
      original_preview: "Payment is due within thirty days.",
      original_risk_terms: [],
      modified_clause_id: "clause-001",
      modified_title: "Payment",
      modified_preview: "Payment is due immediately on demand.",
      modified_risk_terms: ["on demand"],
    },
    {
      status: "unchanged",
      similarity: 1,
      original_clause_id: "clause-002",
      original_title: "Notices",
      original_preview: "Notices must be in writing.",
      modified_clause_id: "clause-002",
      modified_title: "Notices",
      modified_preview: "Notices must be in writing.",
    },
  ],
  risk_signals: [
    {
      type: "new_risk_term",
      clause: "Payment",
      detail: "The modified clause introduces payment on demand.",
      severity: "HIGH",
    },
  ],
  notes: ["Comparison is based on normalized clause text."],
};
